"""
Generator script: parses the vendored VBA source in reference/vbzmanim and
auto-generates the pure-data Python modules under pyzmanim/_data/.

Rationale: mod_shiur.bas / mod_dafyomi.bas / mod_parasha.bas / mod_hdateformat.bas
contain thousands of lines of Hebrew-text lookup tables. Hand-retyping this text
would be slow and error-prone (religious text accuracy matters). Instead we parse
the original VBA assignments directly with regex, which guarantees byte-for-byte
fidelity with upstream and lets us re-run this script whenever
https://github.com/diaphone1/vbzmanim is updated.

Usage:
    python tools/generate_data.py

Requires the reference/vbzmanim folder to exist (see reference/vbzmanim/README.md
for provenance). Files there were re-encoded from Windows-1255 to UTF-8.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF = ROOT / "reference" / "vbzmanim"
OUT = ROOT / "pyzmanim" / "_data"

HEADER = '''"""
AUTO-GENERATED FILE - do not edit by hand.

Generated by tools/generate_data.py from the original VBA source at
https://github.com/diaphone1/vbzmanim (vendored under reference/vbzmanim/).
Re-run tools/generate_data.py to regenerate after pulling upstream changes.
"""
'''

ASSIGN_1D_RE = re.compile(
    r'^\s*(\w+)\(\s*(\d+)\s*\)\s*=\s*"((?:[^"]|"")*)"'
)
ASSIGN_2D_RE = re.compile(
    r'^\s*(\w+)\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*=\s*"((?:[^"]|"")*)"'
)
ASSIGN_2D_ENUM_RE = re.compile(
    r'^\s*(\w+)\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*=\s*(\w+)\s*$'
)


def unescape_vba_string(s: str) -> str:
    return s.replace('""', '"')


def parse_1d_arrays(text: str, names: list[str]) -> dict[str, dict[int, str]]:
    result: dict[str, dict[int, str]] = {name: {} for name in names}
    for line in text.splitlines():
        m = ASSIGN_1D_RE.match(line)
        if not m:
            continue
        name, idx, value = m.group(1), int(m.group(2)), m.group(3)
        if name in result:
            result[name][idx] = unescape_vba_string(value)
    return result


def parse_2d_string_array(text: str, name: str) -> dict[tuple[int, int], str]:
    result: dict[tuple[int, int], str] = {}
    for line in text.splitlines():
        m = ASSIGN_2D_RE.match(line)
        if not m or m.group(1) != name:
            continue
        row, col, value = int(m.group(2)), int(m.group(3)), m.group(4)
        result[(row, col)] = unescape_vba_string(value)
    return result


def parse_2d_enum_array(text: str, name: str) -> dict[tuple[int, int], str]:
    result: dict[tuple[int, int], str] = {}
    for line in text.splitlines():
        m = ASSIGN_2D_ENUM_RE.match(line)
        if not m or m.group(1) != name:
            continue
        row, col, value = int(m.group(2)), int(m.group(3)), m.group(4)
        result[(row, col)] = value
    return result


def dict_to_list(d: dict[int, str], size: int, default: str = "") -> list[str]:
    return [d.get(i, default) for i in range(size)]


def emit_list_literal(varname: str, values: list[str], out_lines: list[str]) -> None:
    out_lines.append(f"{varname} = [")
    for v in values:
        out_lines.append(f"    {v!r},")
    out_lines.append("]")
    out_lines.append("")


def emit_grid_literal(
    varname: str,
    grid: dict[tuple[int, int], str],
    rows: int,
    cols: int,
    default: str = "",
    out_lines: list[str] | None = None,
) -> None:
    assert out_lines is not None
    out_lines.append(f"{varname} = [")
    for r in range(rows):
        row_values = [grid.get((r, c), default) for c in range(cols)]
        out_lines.append(f"    {row_values!r},")
    out_lines.append("]")
    out_lines.append("")


# ---------------------------------------------------------------------------
# mod_parasha.bas -> parasha_data.py  (17 x 56 grid of Parshah enum-name strings)
# ---------------------------------------------------------------------------
def generate_parasha_data() -> None:
    text = (REF / "mod_parasha.bas").read_text(encoding="utf-8")
    grid = parse_2d_enum_array(text, "parashaList")
    max_row = max(r for r, _ in grid) + 1
    max_col = max(c for _, c in grid) + 1
    out: list[str] = [HEADER, ""]
    emit_grid_literal(
        "PARASHA_LIST", grid, max_row, max_col, default="NOPARSHAH", out_lines=out
    )
    (OUT / "parasha_data.py").write_text("\n".join(out), encoding="utf-8")
    print(f"parasha_data.py: {max_row}x{max_col} grid")


# ---------------------------------------------------------------------------
# mod_hdateformat.bas -> hdateformat_data.py
# ---------------------------------------------------------------------------
YOMTOV_ORDER = [
    "CHOL", "PESACH_DAY1", "PESACH_DAY2", "SHVEI_SHEL_PESACH", "ACHRON_SHEL_PESACH",
    "SHAVOUS_DAY1", "SHAVOUS_DAY2", "ROSH_HASHANAH_DAY1", "ROSH_HASHANAH_DAY2",
    "YOM_KIPPUR", "SUKKOS_DAY1", "SUKKOS_DAY2", "SHMEINI_ATZERES", "SIMCHAS_TORAH",
    "CHOL_HAMOED_PESACH_DAY1", "CHOL_HAMOED_PESACH_DAY2", "CHOL_HAMOED_PESACH_DAY3",
    "CHOL_HAMOED_PESACH_DAY4", "CHOL_HAMOED_PESACH_DAY5",
    "CHOL_HAMOED_SUKKOS_DAY1", "CHOL_HAMOED_SUKKOS_DAY2", "CHOL_HAMOED_SUKKOS_DAY3",
    "CHOL_HAMOED_SUKKOS_DAY4", "CHOL_HAMOED_SUKKOS_DAY5",
    "HOSHANA_RABBAH", "PESACH_SHEINI", "LAG_BAOMER", "TU_BAV",
    "CHANUKAH_DAY1", "CHANUKAH_DAY2", "CHANUKAH_DAY3", "CHANUKAH_DAY4",
    "CHANUKAH_DAY5", "CHANUKAH_DAY6", "CHANUKAH_DAY7", "CHANUKAH_DAY8",
    "TU_BISHVAT", "PURIM_KATAN", "SHUSHAN_PURIM_KATAN", "PURIM", "SHUSHAN_PURIM",
    "SHIVA_ASAR_BTAAMUZ", "TISHA_BAV", "TZOM_GEDALIA", "ASARAH_BTEVES",
    "TAANIS_ESTER", "EREV_PESACH", "EREV_SHAVOUS", "EREV_ROSH_HASHANAH",
    "EREV_YOM_KIPPUR", "EREV_SUKKOS", "SHKALIM", "ZACHOR", "PARAH", "HACHODESH",
    "ROSH_CHODESH", "MACHAR_CHODESH", "SHABBOS_MEVORCHIM", "HAGADOL", "CHAZON",
    "NACHAMU", "SHUVA", "SHIRA", "SHABBOS_CHOL_HAMOED",
]

CASE_LINE_RE = re.compile(r'^\s*Case\s+(.+?):?\s*$')
FORMAT_LINE_RE = re.compile(r'^\s*YomTovFormat\s*=\s*"((?:[^"]|"")*)"\s*$')


def expand_case_targets(case_expr: str) -> list[str]:
    """Expand a VBA `Case A, B, C To D` expression into enum name list."""
    targets: list[str] = []
    for part in case_expr.split(","):
        part = part.strip()
        if " To " in part:
            start_name, end_name = [p.strip() for p in part.split(" To ")]
            start_i = YOMTOV_ORDER.index(start_name)
            end_i = YOMTOV_ORDER.index(end_name)
            targets.extend(YOMTOV_ORDER[start_i:end_i + 1])
        else:
            targets.append(part)
    return targets


def parse_yomtov_format(text: str) -> dict[str, str]:
    lines = text.splitlines()
    in_func = False
    result: dict[str, str] = {}
    pending_targets: list[str] = []
    for line in lines:
        if "Function YomTovFormat" in line:
            in_func = True
            continue
        if not in_func:
            continue
        if line.strip().startswith("End Function"):
            break
        case_m = CASE_LINE_RE.match(line)
        if case_m and not line.strip().startswith("Case Else"):
            pending_targets = expand_case_targets(case_m.group(1))
            continue
        if line.strip().startswith("Case Else"):
            pending_targets = []
            continue
        fmt_m = FORMAT_LINE_RE.match(line)
        if fmt_m and pending_targets:
            value = unescape_vba_string(fmt_m.group(1))
            for t in pending_targets:
                result[t] = value
            pending_targets = []
    return result


def generate_hdateformat_data() -> None:
    text = (REF / "mod_hdateformat.bas").read_text(encoding="utf-8")
    arrays = parse_1d_arrays(text, ["hchar", "hmonth", "hwday", "parshahchar"])
    hchar = dict_to_list(arrays["hchar"], 25, default="?")
    hmonth = dict_to_list(arrays["hmonth"], 14)
    hwday = dict_to_list(arrays["hwday"], 8)
    parshahchar = dict_to_list(arrays["parshahchar"], 62)
    yomtov_format = parse_yomtov_format(text)

    out: list[str] = [HEADER, ""]
    emit_list_literal("HCHAR", hchar, out)
    emit_list_literal("HMONTH", hmonth, out)
    emit_list_literal("HWDAY", hwday, out)
    emit_list_literal("PARSHAHCHAR", parshahchar, out)
    out.append("YOMTOV_FORMAT = {")
    for k, v in yomtov_format.items():
        out.append(f"    {k!r}: {v!r},")
    out.append("}")
    out.append("")
    (OUT / "hdateformat_data.py").write_text("\n".join(out), encoding="utf-8")
    print(f"hdateformat_data.py: {len(yomtov_format)} yomtov format entries")


# ---------------------------------------------------------------------------
# mod_dafyomi.bas -> dafyomi_data.py
# ---------------------------------------------------------------------------
def generate_dafyomi_data() -> None:
    text = (REF / "mod_dafyomi.bas").read_text(encoding="utf-8")
    names = [
        "mishnayos_arr", "masechtosBavli", "masechtosBavliTransliterated",
        "masechtosYerushalmi", "masechtosYerushalmiTransliterated",
    ]
    arrays = parse_1d_arrays(text, names)
    # numeric arrays (blattPerMasechta / blattPerMasechtaYerushalmi) aren't
    # strings; parse them separately.
    blatt_re = re.compile(r'^\s*(blattPerMasechta|blattPerMasechtaYerushalmi)\((\d+)\)\s*=\s*(\d+)\s*$')
    blatt: dict[str, dict[int, int]] = {"blattPerMasechta": {}, "blattPerMasechtaYerushalmi": {}}
    for line in text.splitlines():
        m = blatt_re.match(line)
        if m:
            blatt[m.group(1)][int(m.group(2))] = int(m.group(3))

    out: list[str] = [HEADER, ""]
    emit_list_literal("MISHNAYOS_ARR", dict_to_list(arrays["mishnayos_arr"], 64), out)
    emit_list_literal("MASECHTOS_BAVLI", dict_to_list(arrays["masechtosBavli"], 40), out)
    emit_list_literal(
        "MASECHTOS_BAVLI_TRANSLITERATED",
        dict_to_list(arrays["masechtosBavliTransliterated"], 40), out,
    )
    emit_list_literal("MASECHTOS_YERUSHALMI", dict_to_list(arrays["masechtosYerushalmi"], 39), out)
    emit_list_literal(
        "MASECHTOS_YERUSHALMI_TRANSLITERATED",
        dict_to_list(arrays["masechtosYerushalmiTransliterated"], 39), out,
    )
    blatt_list = [blatt["blattPerMasechta"].get(i, 0) for i in range(40)]
    out.append(f"BLATT_PER_MASECHTA = {blatt_list!r}")
    out.append("")
    blatt_y_list = [blatt["blattPerMasechtaYerushalmi"].get(i, 0) for i in range(39)]
    out.append(f"BLATT_PER_MASECHTA_YERUSHALMI = {blatt_y_list!r}")
    out.append("")
    (OUT / "dafyomi_data.py").write_text("\n".join(out), encoding="utf-8")
    print("dafyomi_data.py generated")


# ---------------------------------------------------------------------------
# mod_shiur.bas -> shiur_data.py
# ---------------------------------------------------------------------------
def generate_shiur_data() -> None:
    text = (REF / "mod_shiur.bas").read_text(encoding="utf-8")
    names = ["TehillimArray", "halachayomi"]
    arrays = parse_1d_arrays(text, names)
    tehillim = dict_to_list(arrays["TehillimArray"], 31)
    halacha = dict_to_list(arrays["halachayomi"], 404)

    # rambamarray3chp / rambamarray1chp can contain very large indices; find max dynamically
    def parse_1d_dynamic(name: str) -> dict[int, str]:
        pattern = re.compile(rf'^\s*{name}\(\s*(\d+)\s*\)\s*=\s*"((?:[^"]|"")*)"')
        result: dict[int, str] = {}
        for line in text.splitlines():
            m = pattern.match(line)
            if m:
                result[int(m.group(1))] = unescape_vba_string(m.group(2))
        return result

    rambam3 = parse_1d_dynamic("rambamarray3chp")
    rambam1 = parse_1d_dynamic("rambamarray1chp")
    rambam3_list = dict_to_list(rambam3, max(rambam3) + 1)
    rambam1_list = dict_to_list(rambam1, max(rambam1) + 1)

    tanya_regular = parse_2d_string_array(text, "tanyaarrayregular")
    tanya_leap = parse_2d_string_array(text, "tanyaarrayleap")

    out: list[str] = [HEADER, ""]
    emit_list_literal("TEHILLIM_ARRAY", tehillim, out)
    emit_list_literal("HALACHA_YOMI", halacha, out)
    emit_list_literal("RAMBAM_3CHP", rambam3_list, out)
    emit_list_literal("RAMBAM_1CHP", rambam1_list, out)
    emit_grid_literal("TANYA_REGULAR", tanya_regular, 13, 32, out_lines=out)
    emit_grid_literal("TANYA_LEAP", tanya_leap, 14, 32, out_lines=out)
    (OUT / "shiur_data.py").write_text("\n".join(out), encoding="utf-8")
    print(
        f"shiur_data.py: tehillim={len(tehillim)} halacha={len(halacha)} "
        f"rambam3={len(rambam3_list)} rambam1={len(rambam1_list)}"
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    init_file = OUT / "__init__.py"
    if not init_file.exists():
        init_file.write_text("", encoding="utf-8")
    generate_parasha_data()
    generate_hdateformat_data()
    generate_dafyomi_data()
    generate_shiur_data()


if __name__ == "__main__":
    main()
